//
//  LocalizableStrings.swift
//  Fireblocks
//
//  Created by Fireblocks Ltd. on 25/06/2023.
//

import Foundation

struct LocalizableStrings{
    static let biometricsEmailOrPassIncorrectTryAgain = "biometrics_email_or_pass_incorrect_try_again".localize()
    static let biometricsOpenSettingsToProvideAccess = "biometrics_open_settings_to_provide_access".localize()
    static let biometricsNotEnrolled = "biometrics_not_enrolled".localize()
    static let biometricsFailedGeneral =  "biometrics_failed_general".localize()
    static let biometricsCredentialsNotSaved = "biometrics_credentials_not_saved".localize()
    static let biometricsLoginWithTouchId = "biometrics_login_with_touchid".localize()
    static let biometricsLoginWithFaceId = "biometrics_login_with_faceid".localize()
    static let biometricsAccessExplanation = "biometrics_access_explanation".localize()
    static let loginGoogleSignIn = "login_google_sign_in".localize()
    static let loginAppleSignIn = "login_apple_sign_in".localize()
    static let loginGoogleSignUp = "login_google_sign_up".localize()
    static let loginAppleSignUP = "login_apple_sign_up".localize()
    static let loginGoogleAddDevice = "login_google_add_device".localize()
    static let loginAppleAddDevice = "login_apple_add_device".localize()
    static let signInTitle = "sign_in_title".localize()
    static let signUpTitle = "sign_up_title".localize()
    static let addDeviceTitle = "add_device_title".localize()
    static let areYouSure = "are_you_sure".localize()
    static let continueTitle = "continue".localize()
    static let confirm = "confirm".localize()
    static let neverMind = "never_mind".localize()
    static let singOutConfirmation = "sign_out_confirmation".localize()
    static let signOut = "sign_out".localize()
    static let createABackup = "create_a_backup".localize()
    static let recoverWallet = "recover_wallet".localize()
    static let exportPrivateKey = "export_private_key".localize()
    static let advancedInfo = "advanced_info".localize()
    static let signUpFailed = "sign_up_failed".localize()
    static let mpcKeysGenerationFailed = "mpc_keys_generation_failed".localize()
    static let accountCreationFailed = "account_creation_failed".localize()
    static let signInFailed = "sign_in_failed".localize()
    static let addDeviceFailed = "add_device_failed".localize()
    static let failedToCreateKeyBackup = "failed_to_create_key_backup".localize()
    static let failedToRecoverWallet = "failed_to_recover_wallet".localize()
    static let failedToFindValidRecoveryKey = "failed_to_find_valid_recovery_key".localize()
    static let recoveryKeyIsIncorrect = "recovery_key_is_incorrect".localize()
    static let failedToApproveTransaction = "failed_to_approve_transaction".localize()
    static let takeoverWarningTitle = "takeover_warning_title".localize()
    static let takeoverWarningDescription = "takeover_warning_description".localize()
    static let walletRecoveredSuccessfully = "wallet_recovered_successfully".localize()
    static let googleDrive = "google_drive".localize()
    static let iCloud = "icloud".localize()
    static let externalLocation = "external_location".localize()
    static let backupDateAndAccount = "backup_date_and_account".localize()
    static let createPrivateKey = "create_a_private_key".localize()
    static let copyKey = "copy_key".localize()
    static let recoverTitle = "recover_title".localize()
    static let recoverFromDrive = "recover_from_drive".localize()
    static let recoverFromICloud = "recover_from_icloud".localize()
    static let recoverManually = "recover_manually".localize()
    static let copyAndPasteYourRecoveryKey = "copy_and_paste_your_recovery_key".localize()
    static let createKeyBackup = "create_key_backup".localize()
    static let saveRecoveryKey = "save_recovery_key".localize()
    static let copyRecoveryKey = "copy_recovery_key".localize()
    static let takeoverPrivateKey = "takeover_private_key".localize()
    static let recoverWalletTitle = "recover_wallet_title".localize()
    static let exportPrivateKeyTitle = "export_private_key_title".localize()
    static let backupExplanation = "backup_explanation".localize()
    static let backupOnDrive = "backup_on_drive".localize()
    static let backupOnICloud = "backup_on_icloud".localize()
    static let backupManually = "backup_manually".localize()
    static let tryAgain = "try_again".localize()
    static let chooseRecoveryLocation = "choose_recovery_location".localize()
    static let copied = "copied".localize()
    static let feeActivityIndicatorMessage = "feeInfoMessage".localize()
    static let generateKeysButtonTitle = "generate_keys_button_title".localize()
    static let generateKeysIndicatorMessage = "generate_keys_indicator_message".localize()
    static let preparingDeviceIndicatorMessage = "preparing_device_indicator_message".localize()
    
    static let failedCreateTransaction = "failed_create_transaction".localize()
    static let failedToGetTransactionInfo = "failed_to_get_transaction_info".localize()
    static let approveTxFailed = "approveTxFailed".localize()
    static let cancelTxFailed = "cancelTxFailed".localize()
    static let generateMPCKeys = "generateMPCKeys".localize()
    static let didGenerateMPCKeysSuccessTitle = "didGenerateMPCKeysSuccessTitle".localize()
    static let illDoThisLater = "illDoThisLater".localize()
    
    static let mpcKeysGenertaeTitle = "mpc_keys_genertae_title".localize()
    static let mpcKeysAddDeviceTitle = "mpc_keys_add_device_title".localize()
    static let mpcKeysAddDeviceHeader = "mpc_keys_add_device_header".localize()
    static let shareLogs = "share_logs".localize()
    static let addNewDevice = "add_new_device".localize()
    static let addNewDeviceNavigationBar = "add_new_device_navigation_bar".localize()
    
    static let approveJoinWalletSucceeded = "approveJoinWalletSucceeded".localize()
    static let approveJoinWalletFailed = "approveJoinWalletFailed".localize()
    static let approveJoinWalletCanceled = "approveJoinWalletCanceled".localize()
    static let approveJoinWalletCanceledSubtitle = "approveJoinWalletCanceledSubtitle".localize()
    static let goHome = "goHome".localize()
    static let addDeviceAdded = "addDeviceAdded".localize()
    static let addDeviceFailedTitle = "addDeviceFailedTitle".localize()
    static let addDeviceFailedSubtitle = "addDeviceFailedSubtitle".localize()
    static let addDeviceFailedToGenerateQR = "addDeviceFailedToGenerateQR".localize()

    static let launchOnExistingDevice = "launchOnExistingDevice".localize()
    static let openSettingsMenu = "openSettingsMenu".localize()
    static let tapAddNewDevice = "tapAddNewDevice".localize()
    static let scanTheQRCode = "scanTheQRCode".localize()
    static let scanQRCode = "scanQRCode".localize()
    static let qrCodeExpiresIn = "qrCodeExpiresIn".localize()
    static let qrCodeLink = "qrCodeLink".localize()
    static let prepareForScanHeader = "prepareForScanHeader".localize()
    static let enterQRCodeLink = "enterQRCodeLink".localize()
    static let copyQRCodeLink = "copyQRCodeLink".localize()
}
